table dim_date
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: Long Date
		summarizeBy: none
		sourceColumn: date

	column year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: string
		summarizeBy: none
		sourceColumn: quarter

	column month_number
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: month_number

	column month_name
		dataType: string
		summarizeBy: none
		sortByColumn: month_number
		sourceColumn: month_name

	column year_month
		dataType: string
		summarizeBy: none
		sourceColumn: year_month

	column week
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: week

	column day_name
		dataType: string
		summarizeBy: none
		sourceColumn: day_name

	column is_weekend
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_weekend

	partition dim_date = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(PromotedHeaders, {{"date", type date}, {"year", Int64.Type}, {"quarter", type text}, {"month_number", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"week", Int64.Type}, {"day_name", type text}, {"is_weekend", type logical}}, "en-US")
				in
					Typed
