table dim_date
	lineageTag: 3f240fa9-65c4-463f-8ad6-0fbbf7c164de
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 7121e0fb-3233-42ce-8733-759611d7fbb2
		summarizeBy: none
		sourceColumn: date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 9f9c27e0-56bd-417e-8191-7f27fa464207
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: string
		lineageTag: f127282d-5e8c-4c86-a32e-7f681581bf7d
		summarizeBy: none
		sourceColumn: quarter

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: ce35f275-fdab-42c3-a172-66324c7722ef
		summarizeBy: none
		sourceColumn: month_number

	column month_name
		dataType: string
		lineageTag: 59e91b4a-8a0f-4b32-8c0f-6796ce7df21a
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_number

	column year_month
		dataType: string
		lineageTag: d5d6235b-acb1-4fde-93b6-85b2f1931246
		summarizeBy: none
		sourceColumn: year_month

	column week
		dataType: int64
		formatString: 0
		lineageTag: b85dc98f-d9b4-4982-bd6a-e0e96fe527db
		summarizeBy: none
		sourceColumn: week

	column day_name
		dataType: string
		lineageTag: aae5621a-1d9c-410a-bdc1-4718ea11f1f1
		summarizeBy: none
		sourceColumn: day_name

	column is_weekend
		dataType: boolean
		lineageTag: ca811727-6fda-4dab-9011-e7f0e9fde087
		summarizeBy: none
		sourceColumn: is_weekend

	partition dim_date = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(PromotedHeaders, {{"date", type date}, {"year", Int64.Type}, {"quarter", type text}, {"month_number", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"week", Int64.Type}, {"day_name", type text}, {"is_weekend", type logical}}, "en-US")
				in
					Typed

