table dim_product

	column stock_code
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: stock_code

	column description
		dataType: string
		summarizeBy: none
		sourceColumn: description

	column category
		dataType: string
		summarizeBy: none
		sourceColumn: category

	column units_sold
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: units_sold

	column revenue
		dataType: double
		formatString: £#,0.00
		summarizeBy: sum
		sourceColumn: revenue

	column est_profit
		dataType: double
		formatString: £#,0.00
		summarizeBy: sum
		sourceColumn: est_profit

	column n_orders
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: n_orders

	column first_sold
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: first_sold

	column last_sold
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: last_sold

	column sales_velocity
		dataType: double
		formatString: #,0.0
		summarizeBy: average
		sourceColumn: sales_velocity

	column days_since_sale
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: days_since_sale

	column movement
		dataType: string
		summarizeBy: none
		sourceColumn: movement

	column restock_recommended
		dataType: boolean
		summarizeBy: none
		sourceColumn: restock_recommended

	partition dim_product = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\dim_product.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(PromotedHeaders, {{"stock_code", type text}, {"description", type text}, {"category", type text}, {"units_sold", Int64.Type}, {"revenue", type number}, {"est_profit", type number}, {"n_orders", Int64.Type}, {"first_sold", type datetime}, {"last_sold", type datetime}, {"sales_velocity", type number}, {"days_since_sale", Int64.Type}, {"movement", type text}, {"restock_recommended", type logical}}, "en-US")
				in
					Typed
