table dim_customer

	column customer_id
		dataType: int64
		isKey
		summarizeBy: none
		sourceColumn: customer_id

	column recency_days
		dataType: int64
		formatString: #,0
		summarizeBy: average
		sourceColumn: recency_days

	column frequency
		dataType: int64
		formatString: #,0
		summarizeBy: average
		sourceColumn: frequency

	column lifetime_value
		dataType: double
		formatString: £#,0.00
		summarizeBy: sum
		sourceColumn: lifetime_value

	column first_purchase
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: first_purchase

	column country
		dataType: string
		dataCategory: Country
		summarizeBy: none
		sourceColumn: country

	column avg_order_value
		dataType: double
		formatString: £#,0.00
		summarizeBy: average
		sourceColumn: avg_order_value

	column cluster
		dataType: int64
		summarizeBy: none
		sourceColumn: cluster

	column segment
		dataType: string
		summarizeBy: none
		sourceColumn: segment

	partition dim_customer = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\dim_customer.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(PromotedHeaders, {{"customer_id", Int64.Type}, {"recency_days", Int64.Type}, {"frequency", Int64.Type}, {"lifetime_value", type number}, {"first_purchase", type datetime}, {"country", type text}, {"avg_order_value", type number}, {"cluster", Int64.Type}, {"segment", type text}}, "en-US")
				in
					Typed
