table dim_customer
	lineageTag: 07663e2d-b4cb-48c8-8779-8e71c125a6bf

	column customer_id
		dataType: int64
		isKey
		lineageTag: 45180a91-a390-40c4-80df-043c4b1bbcfa
		summarizeBy: none
		sourceColumn: customer_id

	column recency_days
		dataType: int64
		formatString: #,0
		lineageTag: 7a08a538-9e0a-4f3e-877a-4838cca2b832
		summarizeBy: average
		sourceColumn: recency_days

	column frequency
		dataType: int64
		formatString: #,0
		lineageTag: bb86729e-d464-401a-a52b-fff9d9603e98
		summarizeBy: average
		sourceColumn: frequency

	column lifetime_value
		dataType: double
		formatString: £#,0.00
		lineageTag: 736285d3-ef4e-4b48-8c30-798b716734d1
		summarizeBy: sum
		sourceColumn: lifetime_value

	column first_purchase
		dataType: dateTime
		formatString: General Date
		lineageTag: 1c942f00-3d8f-4018-b98d-80f92329c82c
		summarizeBy: none
		sourceColumn: first_purchase

	column country
		dataType: string
		lineageTag: bdb16957-48e3-4799-8432-7546260b28b5
		dataCategory: Country
		summarizeBy: none
		sourceColumn: country

	column avg_order_value
		dataType: double
		formatString: £#,0.00
		lineageTag: 13eda6fb-8214-4016-9d32-019cbbdbc638
		summarizeBy: average
		sourceColumn: avg_order_value

	column cluster
		dataType: int64
		lineageTag: 2f07d2bb-0339-4ab9-883e-d522b71c3888
		summarizeBy: none
		sourceColumn: cluster

	column segment
		dataType: string
		lineageTag: 7182e59c-5685-4289-8038-bb141f84c0f4
		summarizeBy: none
		sourceColumn: segment

	partition dim_customer = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\dim_customer.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(PromotedHeaders, {{"customer_id", Int64.Type}, {"recency_days", Int64.Type}, {"frequency", Int64.Type}, {"lifetime_value", type number}, {"first_purchase", type datetime}, {"country", type text}, {"avg_order_value", type number}, {"cluster", Int64.Type}, {"segment", type text}}, "en-US")
				in
					Typed

